language: python
python:
- '3.5'
install:
- pip install .
script:
- python setup.py test
deploy:
- provider: releases
  api_key:
    secure: mWdLXjWAbioxRdJ0XGFYm6WeV90W+ZaabQHCjlnFVX576hJqyQabs9pkHoF/VnanecEtoOVzt7cZdmZQ+mNoZgbSE+90iGZosZO0GZFX7MjhxYw5bJOUmRr9L+/6cV7v+XEE8cFQTFCQgMPycWOjvnyuRixLGDVn/l1MeUc84xpSD7T4XwIZlwX9YB6fKAtvuz9vq5xQwV8mJOtIWN3NqlVuhdew7WkUdq0eiRK5dm1G05o/tiKfxCI+76fyRr6FLmzs7WH/CS5spbMpr6bv9iBirOYK57Jr5xdS1zE4mnwaJ8vIubbjO7BN4H8AjwdMzUBF96X2nRVRluGi0sGbbBEQiGCOg2Qtjb3udGaekmPYF6DRwQZMhBtvsd2B31gIhRps2qQigiZUfqnWr3p4Uoua5+2yOfVJUuHxbBLvlag4qbfGr1LZg/lRt58WGydtwfqXuKVlEUyhQvqd7AGfwVOVRW3ezmpqerMRNSHzkf+XnuB/A3/7FEY1xdMbez6yDqxbp8Jm7qmscwnt+7SR14Ur63jSv+qeact6z9H60mFCOWO5533rtfNDIHO6Av7N+IgeOG8i30K+OgWWa2vXWqrjrBEttFs0qi9O3PAMImXkw/iiHlCYkFDDwyTZCzYUQA1LiBP5q+8IfEj8up58NxM6wvB1TrVi2jEq29GHX3Y=
  name: diskarray-0.1.9
  tag_name: 0.1.9
  on:
    repo: deep-compute/diskarray
- provider: pypi
  distributions: "sdist bdist_wheel"
  server: https://upload.pypi.org/legacy/
  user: deepcompute
  password:
    secure: "XScKeAhmF7gGThEjJCtur1RHlGUZ2n3FXukp7619YHmLoUzvszo8Wg+ZSJrdl3soEuSvVQdn2G3ngxAZdKmNhWVYrUKRdKL5iY4WyYHVujkOq+diVqCGHWbSmZJupyscgt1L/H8l+IohC1dnng/ThQuFp7Jbay68lM8LzS20f16JgSL6Xq+jRqqtBU3jALoqf9scnwuXG+Yj51YTQ9DmS37ctlLyzg3GEbICQB1dNaSZ3HtM1LB0/69++rhukzicm1Z9FcNEbdL9U7ohAgrI1+0mj/4xtURIrOwvlKjhjXUxf5S2RMe49xFq4KDRkXL8uwUEvRnskwXH6u0+mkAQRpMYFMygxcmiVhuhhelJD43RuO56o84IWQLAwje/RUeH1huePUNBV63tAXQC1uQ4yoaZs/DehtjDjgIkk/j4xdTnlwaN68icGrnWxZ5QCwZkz16OQ84HolTLGG9X1Fuqs7iYGI9GmBYfSG6FVp6H6E1Cakvc492gAVqIJKln6Y5u8a1SPpHp2jhhqzsMQo/fwqDTc8m59ENX1zxcIgtJjaWrgkJ4U+W4GBosKpevTJCLKzpirsfJ2Al/7E7rTEOpXpw3NNeeyben708/RiPbWVvhE6yZ7Z6XHYzIO+fF9gr0pRiqdL3uL3ASCUlNEBvw5j7adH57foeTf8mZkQqLyrU="
  on:
    tags: true
    branch: master
